name: Build

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    paths:
      - 'src/*'

jobs:
  build_linux:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libfcitx-qt5-dev fcitx-frontend-qt5
    - name: Update pip (Ubuntu-16.05)
      run: |
           pip3 install --upgrade pip
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.12.1
      with:
        aqtversion: '==0.9.5'
        py7zrversion: '==0.10.1'

    - name: do build
      run: |
        cp /usr/lib/x86_64-linux-gnu/libFcitxQt5DBusAddons.so* $Qt5_Dir/lib/
        cp /usr/lib/x86_64-linux-gnu/libFcitxQt5WidgetsAddons.so* $Qt5_Dir/lib
        cp /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so $Qt5_Dir/plugins/platforminputcontexts/
        cd src
        ./release_linux.sh

  build_mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.10.0
      with:
        mirror: 'http://mirrors.ocf.berkeley.edu/qt/'

    - name: do build
      run: cd src;./release_macos.sh
    
  build_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.10.0
      with:
        mirror: 'http://mirrors.ocf.berkeley.edu/qt/'

    - name: do build
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        cd src
        release_win.bat
