name: Sync
on: [gollum]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Sync to Gitee Wiki
            uses: wearerequired/git-mirror-action@master
            env:
                SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
            with:
                source-repo: "https://github.com/compilelife/loginsight.wiki.git"
                destination-repo: "git@gitee.com:compilelife/loginsight.wiki.git"